version: '3.1'

services:
  postgres:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demo_spring_data_batch
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
