spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_spring_data_batch
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: true
        show_sql: true
        format_sql: false
#        order_inserts: true
#        order_updates: true
#        jdbc:
#          batch_size: 5
